import { useState } from 'react'
import { useAppData } from '@/hooks/useAppData'
import type { Entry } from '@/lib/app-types'
import { DEPARTMENTS } from '@/lib/constants'
import { Newspaper, Copy, Check, WifiOff } from 'lucide-react'

function generateLocalNewsletter(entries: Entry[], dept: string, dateRange: string): string {
  const rangeLabel = dateRange === 'week' ? 'Past Week'
    : dateRange === 'month' ? 'Past Month'
    : dateRange === 'quarter' ? 'Past Quarter'
    : 'All Time'

  const highlights  = entries.filter(e => e.priority === 'Key highlight')
  const highs       = entries.filter(e => e.priority === 'High')
  const byType      = entries.reduce<Record<string, Entry[]>>((acc, e) => {
    acc[e.type] = acc[e.type] || []
    acc[e.type].push(e)
    return acc
  }, {})

  let out = `PARUL UNIVERSITY KNOWLEDGE HUB\n`
  out += `${dept ? dept + ' Department ' : ''}Newsletter · ${rangeLabel}\n`
  out += `${'═'.repeat(50)}\n\n`

  if (highlights.length > 0) {
    out += `🌟 KEY HIGHLIGHTS\n${'─'.repeat(30)}\n`
    highlights.forEach(e => {
      out += `\n• ${e.title}\n`
      out += `  ${e.dept} | ${e.type} | ${e.entry_date}\n`
      out += `  ${e.body?.slice(0, 200)}${(e.body?.length || 0) > 200 ? '…' : ''}\n`
    })
    out += '\n'
  }

  if (highs.length > 0) {
    out += `📌 IMPORTANT UPDATES\n${'─'.repeat(30)}\n`
    highs.forEach(e => {
      out += `\n• ${e.title} (${e.dept})\n`
      out += `  ${e.body?.slice(0, 150)}${(e.body?.length || 0) > 150 ? '…' : ''}\n`
    })
    out += '\n'
  }

  Object.entries(byType)
    .filter(([type]) => type !== 'Achievement' || highlights.length === 0)
    .slice(0, 4)
    .forEach(([type, items]) => {
      out += `${type.toUpperCase()}\n${'─'.repeat(30)}\n`
      items.slice(0, 3).forEach(e => {
        out += `• ${e.title} (${e.dept}, ${e.entry_date})\n`
      })
      if (items.length > 3) out += `  …and ${items.length - 3} more\n`
      out += '\n'
    })

  out += `${'─'.repeat(50)}\n`
  out += `Total entries this period: ${entries.length}\n`
  out += `Generated by Parul University Knowledge Hub\n`
  out += `\n*(AI generation unavailable — this newsletter was built from local data.)*`

  return out
}

export default function AINewsletterPage() {
  const { entries: allEntries } = useAppData()
  const [deptFilter, setDeptFilter] = useState('')
  const [dateRange, setDateRange]   = useState('month')
  const [output, setOutput]         = useState('')
  const [loading, setLoading]       = useState(false)
  const [copied, setCopied]         = useState(false)

  function generate() {
    setLoading(true)
    setOutput('')

    let entries = allEntries
    if (deptFilter) entries = entries.filter(e => e.dept === deptFilter)

    const now = new Date()
    if (dateRange === 'week') {
      const cutoff = new Date(now.getTime() - 7 * 86400000).toISOString().slice(0, 10)
      entries = entries.filter(e => e.entry_date >= cutoff)
    } else if (dateRange === 'month') {
      const cutoff = new Date(now.getTime() - 30 * 86400000).toISOString().slice(0, 10)
      entries = entries.filter(e => e.entry_date >= cutoff)
    } else if (dateRange === 'quarter') {
      const cutoff = new Date(now.getTime() - 90 * 86400000).toISOString().slice(0, 10)
      entries = entries.filter(e => e.entry_date >= cutoff)
    }

    setTimeout(() => {
      setOutput(generateLocalNewsletter(entries, deptFilter, dateRange))
      setLoading(false)
    }, 500)
  }

  function copyOutput() {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="animate-fade-in">
      <div className="mb-6">
        <h1 className="text-2xl font-serif text-foreground">Newsletter Generator</h1>
        <p className="text-sm text-muted-foreground mt-1">Generate newsletters from your knowledge base</p>
      </div>

      <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-amber-50 border border-amber-200 text-amber-700 text-xs mb-6">
        <WifiOff className="w-3.5 h-3.5 shrink-0" />
        AI backend disconnected. Generating newsletter from local data instead.
      </div>

      <div className="hub-card mb-6">
        <div className="flex items-end gap-4">
          <div className="flex-1">
            <label className="hub-label">Department</label>
            <select className="hub-input" value={deptFilter} onChange={e => setDeptFilter(e.target.value)}>
              <option value="">All departments</option>
              {DEPARTMENTS.map(d => <option key={d}>{d}</option>)}
            </select>
          </div>
          <div className="flex-1">
            <label className="hub-label">Time period</label>
            <select className="hub-input" value={dateRange} onChange={e => setDateRange(e.target.value)}>
              <option value="week">Past week</option>
              <option value="month">Past month</option>
              <option value="quarter">Past quarter</option>
              <option value="all">All time</option>
            </select>
          </div>
          <button onClick={generate} disabled={loading}
            className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-brand-dark transition-colors disabled:opacity-50 shrink-0">
            <Newspaper className="w-4 h-4" />
            {loading ? 'Generating...' : 'Generate newsletter'}
          </button>
        </div>
      </div>

      {output && (
        <div className="hub-card">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-foreground">Generated Newsletter</h2>
            <button onClick={copyOutput}
              className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors">
              {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <div className="prose prose-sm max-w-none text-foreground/90 whitespace-pre-wrap leading-relaxed font-mono text-xs">
            {output}
          </div>
        </div>
      )}
    </div>
  )
}
